language: php

php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - mkdir -p build/coverage
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/php-coveralls
