language: php

php:
  - 8.0
  - 8.1
  - 8.2

before_script:
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - mkdir -p build/coverage
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/php-coveralls
